-- USE classicmodels;
-- Soal 1
-- SELECT * FROM employees;
-- INSERT INTO employees (employeeNumber, lastName, firstName, extension, email, officeCode, reportsTo, jobTitle)
-- VALUE (2705, 'Azyumardi', 'Hasan', x6969, 'tchkz@chakz.com',1, 1056,'Major');
-- 
-- INSERT INTO employees (employeeNumber, lastName, firstName, extension, email, officeCode, reportsTo, jobTitle)
-- VALUE (2706, 'Khidlir', 'Karawita', 'x3322', 'khdlr@kumang.com', 1, 1702, 'Vice Admiral');
-- 
-- INSERT INTO employees (employeeNumber, lastName, firstName, extension, email, officeCode, reportsTo, jobTitle)
-- VALUE (2707, 'Khalid', 'Kashmiri', 'x3219','khld@sportrecing.com', 7 , 1088, 'Lawyer');
-- -- 
-- -- Soal 2
-- SELECT * FROM offices;
-- INSERT INTO offices (officeCode, city, phone, addressLine1, addressLine2, state, country, postalCode, territory)
-- VALUE (8, 'West Edgardofort', '+(874) 824-4874', '7316 Keefe Ford', NULL, 'Maryland', 'USA', 80166, 'NA');
-- 
-- SELECT * FROM employees;
-- UPDATE employees
-- SET officeCode = 8
-- WHERE  jobTitle = 'Sales Rep'AND officeCode = 4;
-- 
-- SELECT * FROM employees 
-- WHERE jobtitle= 'Sales Rep' AND officeCode= 4;
-- 
-- Soal 3
-- SELECT * FROM payments
-- DELETE FROM payments WHERE amount<10000;
-- 